Hop.create(category: 'American', max_alpha_acid: 0.065, min_alpha_acid: 0.035, name: 'Ahthanum')
Hop.create(category: 'American', max_alpha_acid: 0.11, min_alpha_acid: 0.08, name: 'Amarillo')
Hop.create(category: 'American', max_alpha_acid: 0.21, min_alpha_acid: 0.18, name: 'Apollo')
Hop.create(category: 'American', max_alpha_acid: 0.19, min_alpha_acid: 0.15, name: 'Bravo')
Hop.create(category: 'American', max_alpha_acid: 0.14, min_alpha_acid: 0.12, name: 'Calypso')
Hop.create(category: 'American', max_alpha_acid: 0.07, min_alpha_acid: 0.045, name: 'Cascade')
Hop.create(category: 'American', max_alpha_acid: 0.12, min_alpha_acid: 0.09, name: 'Centennial')
Hop.create(category: 'American', max_alpha_acid: 0.145, min_alpha_acid: 0.12, name: 'Chelan')
Hop.create(category: 'American', max_alpha_acid: 0.14, min_alpha_acid: 0.12, name: 'Chinook')
Hop.create(category: 'American', max_alpha_acid: 0.12, min_alpha_acid: 0.10, name: 'Citra')
Hop.create(category: 'American', max_alpha_acid: 0.085, min_alpha_acid: 0.055, name: 'Cluster')
Hop.create(category: 'American', max_alpha_acid: 0.16, min_alpha_acid: 0.14, name: 'Columbus')
Hop.create(category: 'American', max_alpha_acid: 0.125, min_alpha_acid: 0.095, name: 'Comet')
Hop.create(category: 'American', max_alpha_acid: 0.055, min_alpha_acid: 0.035, name: 'Crystal')
Hop.create(category: 'American', max_alpha_acid: 0.16, min_alpha_acid: 0.14, name: 'El Dorado')
Hop.create(category: 'American', max_alpha_acid: 0.15, min_alpha_acid: 0.12, name: 'Eroica')
Hop.create(category: 'American', max_alpha_acid: 0.135, min_alpha_acid: 0.115, name: 'Galena')
Hop.create(category: 'American', max_alpha_acid: 0.097, min_alpha_acid: 0.033, name: 'Glacier')
Hop.create(category: 'American', max_alpha_acid: 0.055, min_alpha_acid: 0.055, name: 'Greenburg')
Hop.create(category: 'American', max_alpha_acid: 0.155, min_alpha_acid: 0.1, name: 'Horizon')
Hop.create(category: 'American', max_alpha_acid: 0.06, min_alpha_acid: 0.03, name: 'Liberty')
Hop.create(category: 'American', max_alpha_acid: 0.15, min_alpha_acid: 0.11, name: 'Millenium')
Hop.create(category: 'American', max_alpha_acid: 0.06, min_alpha_acid: 0.04, name: 'Mount Hood')
Hop.create(category: 'American', max_alpha_acid: 0.08, min_alpha_acid: 0.06, name: 'Mount Rainier')
Hop.create(category: 'American', max_alpha_acid: 0.17, min_alpha_acid: 0.145, name: 'Newport')
Hop.create(category: 'American', max_alpha_acid: 0.14, min_alpha_acid: 0.095, name: 'Nugget')
Hop.create(category: 'American', max_alpha_acid: 0.095, min_alpha_acid: 0.055, name: 'Palisade')
Hop.create(category: 'American', max_alpha_acid: 0.0701, min_alpha_acid: 0.0701, name: 'San Juan Ruby Red')
Hop.create(category: 'American', max_alpha_acid: 0.084, min_alpha_acid: 0.048, name: 'Santiam')
Hop.create(category: 'American', max_alpha_acid: 0.14, min_alpha_acid: 0.125, name: 'Satus')
Hop.create(category: 'American', max_alpha_acid: 0.14, min_alpha_acid: 0.12, name: 'Simcoe')
Hop.create(category: 'American', max_alpha_acid: 0.066, min_alpha_acid: 0.066, name: 'Sonnet Golding')
Hop.create(category: 'American', max_alpha_acid: 0.09, min_alpha_acid: 0.06, name: 'Sterling')
Hop.create(category: 'American', max_alpha_acid: 0.19, min_alpha_acid: 0.17, name: 'Summit')
Hop.create(category: 'American', max_alpha_acid: 0.16, min_alpha_acid: 0.13, name: 'Super Galena')
Hop.create(category: 'American', max_alpha_acid: 0.145, min_alpha_acid: 0.12, name: 'Tillicum')
Hop.create(category: 'American', max_alpha_acid: 0.17, min_alpha_acid: 0.15, name: 'Tomahawk')
Hop.create(category: 'American', max_alpha_acid: 0.05, min_alpha_acid: 0.04, name: 'Ultra')
Hop.create(category: 'American', max_alpha_acid: 0.06, min_alpha_acid: 0.055, name: 'Vanguard')
Hop.create(category: 'American', max_alpha_acid: 0.17, min_alpha_acid: 0.15, name: 'Warrior')
Hop.create(category: 'American', max_alpha_acid: 0.06, min_alpha_acid: 0.04, name: 'Willamette')
Hop.create(category: 'American', max_alpha_acid: 0.17, min_alpha_acid: 0.15, name: 'Zeus')

Hop.create(category: 'English', max_alpha_acid: 0.162, min_alpha_acid: 0.13, name: 'Admiral')
Hop.create(category: 'English', max_alpha_acid: 0.1, min_alpha_acid: 0.05, name: 'Brewer\'s Gold')
Hop.create(category: 'English', max_alpha_acid: 0.078, min_alpha_acid: 0.05, name: 'Bramling Cross')
Hop.create(category: 'English', max_alpha_acid: 0.09, min_alpha_acid: 0.06, name: 'Bullion')
Hop.create(category: 'English', max_alpha_acid: 0.085, min_alpha_acid: 0.065, name: 'Challenger')
Hop.create(category: 'English', max_alpha_acid: 0.085, min_alpha_acid: 0.065, name: 'First Gold')
Hop.create(category: 'English', max_alpha_acid: 0.06, min_alpha_acid: 0.035, name: 'Fuggles')
Hop.create(category: 'English', max_alpha_acid: 0.06, min_alpha_acid: 0.04, name: 'Goldings')
Hop.create(category: 'English', max_alpha_acid: 0.128, min_alpha_acid: 0.119, name: 'Herald')
Hop.create(category: 'English', max_alpha_acid: 0.095, min_alpha_acid: 0.075, name: 'Northdown')
Hop.create(category: 'English', max_alpha_acid: 0.115, min_alpha_acid: 0.06, name: 'Phoenix')
Hop.create(category: 'English', max_alpha_acid: 0.13, min_alpha_acid: 0.09, name: 'Pilgrim')
Hop.create(category: 'English', max_alpha_acid: 0.12, min_alpha_acid: 0.08, name: 'Pilot')
Hop.create(category: 'English', max_alpha_acid: 0.1, min_alpha_acid: 0.08, name: 'Pioneer')
Hop.create(category: 'English', max_alpha_acid: 0.07, min_alpha_acid: 0.05, name: 'Progress')
Hop.create(category: 'English', max_alpha_acid: 0.125, min_alpha_acid: 0.08, name: 'Target')
Hop.create(category: 'English', max_alpha_acid: 0.07, min_alpha_acid: 0.05, name: 'Whitbread Golding Variety')

Hop.create(category: 'Australia', max_alpha_acid: 0.055, min_alpha_acid: 0.031, name: 'Feux-Coeur Francais')
Hop.create(category: 'Australia', max_alpha_acid: 0.149, min_alpha_acid: 0.149, name: 'Galaxy')
Hop.create(category: 'Australia', max_alpha_acid: 0.10, min_alpha_acid: 0.07, name: 'Pridge of Ringwood')

Hop.create(category: 'Czech Republic', max_alpha_acid: 0.045, min_alpha_acid: 0.03, name: 'Saaz')

Hop.create(category: 'France', max_alpha_acid: 0.05, min_alpha_acid: 0.03, name: 'Strisselspalt')
Hop.create(category: 'France', max_alpha_acid: 0.055, min_alpha_acid: 0.031, name: 'Tardif de Bourgogne')

Hop.create(category: 'Japan', max_alpha_acid: 0.16, min_alpha_acid: 0.10, name: 'Sorachi Ace')

Hop.create(category: 'Slovenia', max_alpha_acid: 0.095, min_alpha_acid: 0.07, name: 'Styrian Aurora')
Hop.create(category: 'Slovenia', max_alpha_acid: 0.07, min_alpha_acid: 0.035, name: 'Styrian Bobek')
Hop.create(category: 'Slovenia', max_alpha_acid: 0.06, min_alpha_acid: 0.045, name: 'Styrian Goldings')
Hop.create(category: 'Slovenia', max_alpha_acid: 0.06, min_alpha_acid: 0.03, name: 'Styrian Celeia')

Hop.create(category: 'Poland', max_alpha_acid: 0.05, min_alpha_acid: 0.03, name: 'Lublin')
Hop.create(category: 'Poland', max_alpha_acid: 0.045, min_alpha_acid: 0.03, name: 'Polnischer Lublin')

Hop.create(category: 'New Zealand', max_alpha_acid: 0.14, min_alpha_acid: 0.11, name: 'Green Bullet')
Hop.create(category: 'Mew Zealand', max_alpha_acid:  0.075, min_alpha_acid: 0.065, name: 'Motueka')
Hop.create(category: 'Nea Zealand', max_alpha_acid: 0.14, min_alpha_acid: 0.12, name: 'Nelson Sauvin')
Hop.create(category: 'New Zealand', max_alpha_acid: 0.08, min_alpha_acid: 0.05, name: 'Pacifica')
Hop.create(category: 'New Zealand', max_alpha_acid: 0.16, min_alpha_acid: 0.14, name: 'Pacific Gem')
Hop.create(category: 'New Zealand', max_alpha_acid: 0.14, min_alpha_acid: 0.12, name: 'Pacific Jade')
Hop.create(category: 'New Zealand', max_alpha_acid: 0.065, min_alpha_acid: 0.0345, name: 'Riwaks')
Hop.create(category: 'New Zealand', max_alpha_acid: 0.14, min_alpha_acid: 0.11, name: 'Southern Cross')

Hop.create(category: 'Germany', max_alpha_acid: 0.55, min_alpha_acid: 0.035, name: 'HellerTau')
Hop.create(category: 'Germany', max_alpha_acid: 0.17, min_alpha_acid: 0.15, name: 'Herkules')
Hop.create(category: 'Germany', max_alpha_acid: 0.055, min_alpha_acid: 0.03, name: 'Hersbrucker')
Hop.create(category: 'Germany', max_alpha_acid: 0.12, min_alpha_acid: 0.1, name: 'Magnum')
Hop.create(category: 'Germany', max_alpha_acid: 0.07, min_alpha_acid: 0.035, name: 'Merkur')
Hop.create(category: 'Germany', max_alpha_acid: 0.055, min_alpha_acid: 0.035, name: 'Opal')
Hop.create(category: 'Germany', max_alpha_acid: 0.1, min_alpha_acid: 0.06, name: 'Perle')
Hop.create(category: 'Germany', max_alpha_acid: 0.045, min_alpha_acid: 0.02, name: 'Saphir')
Hop.create(category: 'Germany', max_alpha_acid: 0.06, min_alpha_acid: 0.04, name: 'Select')
Hop.create(category: 'Germany', max_alpha_acid: 0.055, min_alpha_acid: 0.035, name: 'Smaragd')
Hop.create(category: 'Germany', max_alpha_acid: 0.05, min_alpha_acid: 0.05, name: 'Spalt')
Hop.create(category: 'Germany', max_alpha_acid: 0.06, min_alpha_acid: 0.04, name: 'Taurus')
Hop.create(category: 'Germany', max_alpha_acid: 0.055, min_alpha_acid: 0.035, name: 'Tettnang')
Hop.create(category: 'Germany', max_alpha_acid: 0.07, min_alpha_acid: 0.05, name: 'Tradition')

#Malts
Malt::Grain.create(origin: 'Germany', srm: 3, potential_sg: 1.027, name: 'Acid Malt')
Malt::DryExtract.create(origin: 'US', srm: 13, potential_sg: 1.044, name: 'Amber Dry Extract')
Malt::Extract.create(origin: 'US', srm: 13, potential_sg: 1.036, name: 'Amber Liquid Extract')
Malt::Grain.create(origin: 'United Kingdom', srm: 22, potential_sg: 1.035, name: 'Amber Malt')
Malt::Grain.create(origin: 'Belgium', srm: 26, potential_sg: 1.036, name: 'Aromatic Malt')
Malt::Adjunct.create(origin: 'US', srm: 0, potential_sg: 1.000, name: 'Barley Hulls')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.032, name: 'Barley, Flaked')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.028, name: 'Barley, Raw')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.036, name: 'Barley, Torefied')
Malt::Grain.create(origin: 'Belgium', srm: 23, potential_sg: 1.036, name: 'Biscuit Malt')
Malt::Grain.create(origin: 'US', srm: 500, potential_sg: 1.025, name: 'Black (Patent) Malt')
Malt::Grain.create(origin: 'US', srm: 500, potential_sg: 1.025, name: 'Black Barley (Stout)')
Malt::Grain.create(origin: 'United Kingdom', srm: 65, potential_sg: 1.032, name: 'Brown Malt')
Malt::Sugar.create(origin: 'US', srm: 50, potential_sg: 1.046, name: 'Brown Sugar, Dark')
Malt::Sugar.create(origin: 'US', srm: 8, potential_sg: 1.046, name: 'Brown Sugar, Light')
Malt::Grain.create(origin: 'Germany', srm: 23, potential_sg: 1.033, name: 'Brumalt')
Malt::Sugar.create(origin: 'Belgium', srm: 75, potential_sg: 1.036, name: 'Candi Sugar, Amber')
Malt::Sugar.create(origin: 'Belgium', srm: 1, potential_sg: 1.036, name: 'Candi Sugar, Clear')
Malt::Sugar.create(origin: 'Belgium', srm: 275, potential_sg: 1.036, name: 'Candi Sugar, Dark')
Malt::Sugar.create(origin: 'US', srm: 0, potential_sg: 1.046, name: 'Cane (Beet) Sugar')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.033, name: 'Cara-Pils/Dextrine')
Malt::Grain.create(origin: 'US', srm: 30, potential_sg: 1.035, name: 'Caraamber')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.035, name: 'Carafoam')
Malt::Grain.create(origin: 'US', srm: 10, potential_sg: 1.035, name: 'Caramel/Crystal Malt - 10L')
Malt::Grain.create(origin: 'US', srm: 20, potential_sg: 1.035, name: 'Caramel/Crystal Malt - 20L')
Malt::Grain.create(origin: 'US', srm: 30, potential_sg: 1.035, name: 'Caramel/Crystal Malt - 30L')
Malt::Grain.create(origin: 'US', srm: 40, potential_sg: 1.034, name: 'Caramel/Crystal Malt - 40L')
Malt::Grain.create(origin: 'US', srm: 60, potential_sg: 1.034, name: 'Caramel/Crystal Malt - 60L')
Malt::Grain.create(origin: 'US', srm: 120, potential_sg: 1.033, name: 'Caramel/Crystal Malt - 120L')
Malt::Grain.create(origin: 'Belgium', srm: 56, potential_sg: 1.033, name: 'Caramunich Malt')
Malt::Grain.create(origin: 'US', srm: 20, potential_sg: 1.035, name: 'Carared')
Malt::Grain.create(origin: 'Belgium', srm: 22, potential_sg: 1.034, name: 'Caravienne Malt')
Malt::Grain.create(origin: 'US', srm: 350, potential_sg: 1.028, name: 'Chocolate Malt')
Malt::Grain.create(origin: 'United Kingdom', srm: 450, potential_sg: 1.034, name: 'Chocolate Malt')
Malt::Sugar.create(origin: 'US', srm: 0, potential_sg: 1.046, name: 'Corn Sugar (Dextrose)')
Malt::Sugar.create(origin: 'US', srm: 1, potential_sg: 1.036, name: 'Corn Syrup')
Malt::Grain.create(origin: 'US', srm: 1, potential_sg: 1.037, name: 'Corn, Flaked')
Malt::DryExtract.create(origin: 'US', srm: 18, potential_sg: 1.044, name: 'Dark Dry Extract')
Malt::Extract.create(origin: 'US', srm: 18, potential_sg: 1.036, name: 'Dark Liquid Extract')
Malt::Sugar.create(origin: 'United Kingdom', srm: 2, potential_sg: 1.046, name: 'Dememera Sugar')
Malt::DryExtract.create(origin: 'US', srm: 3, potential_sg: 1.044, name: 'Extra Light Dry Extract')
Malt::Adjunct.create(origin: 'US', srm: 1, potential_sg: 1.037, name: 'Grits')
Malt::Extract.create(origin: 'US', srm: 1, potential_sg: 1.035, name: 'Honey')
Malt::Sugar.create(origin: 'United Kingdom', srm: 0, potential_sg: 1.046, name: 'Invert Sugar')
Malt::DryExtract.create(origin: 'US', srm: 9, potential_sg: 1.044, name: 'Light Dry Extract')
Malt::Sugar.create(origin: 'US', srm: 35, potential_sg: 1.030, name: 'Maple Syrup')
Malt::Grain.create(origin: 'Germany', srm: 20, potential_sg: 1.037, name: 'Melanoiden Malt')
Malt::Grain.create(origin: 'United Kingdom', srm: 4, potential_sg: 1.037, name: 'Mild Malt')
Malt::Sugar.create(origin: 'US', srm: 0, potential_sg: 1.035, name: 'Milk Sugar (Lactose)')
Malt::Sugar.create(origin: 'US', srm: 80, potential_sg: 1.036, name: 'Molasses')
Malt::Grain.create(origin: 'US', srm: 10, potential_sg: 1.035, name: 'Munich Malt - 10L')
Malt::Grain.create(origin: 'US', srm: 20, potential_sg: 1.035, name: 'Munich Malt - 20L')
Malt::Grain.create(origin: 'US', srm: 1, potential_sg: 1.037, name: 'Oats, Flaked')
Malt::Grain.create(origin: 'US', srm: 1, potential_sg: 1.037, name: 'Oats, Malted')
Malt::Grain.create(origin: 'Belgium', srm: 3, potential_sg: 1.037, name: 'Pale Malt (2 Row) Bel')
Malt::Grain.create(origin: 'United Kingdom', srm: 3, potential_sg: 1.036, name: 'Pale Malt (2 Row) UK')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.036, name: 'Pale Malt (2 Row) US')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.035, name: 'Pale Malt (6 Row) US')
Malt::Grain.create(origin: 'United Kingdom', srm: 3, potential_sg: 1.034, name: 'Peat Smoked Malt')
Malt::Grain.create(origin: 'Belgium', srm: 2, potential_sg: 1.036, name: 'Pilsner (2 Row) Bel')
Malt::Grain.create(origin: 'Germany', srm: 2, potential_sg: 1.037, name: 'Pilsner (2 Row) Ger')
Malt::Grain.create(origin: 'United Kingdom', srm: 1, potential_sg: 1.036, name: 'Pilsner (2 Row) UK')
Malt::Extract.create(origin: 'US', srm: 4, potential_sg: 1.036, name: 'Pilsner Liquid Extract')
Malt::Extract.create(origin: 'US', srm: 7, potential_sg: 1.032, name: 'Rice Extract Syrup')
Malt::Adjunct.create(origin: 'US', srm: 0, potential_sg: 1.000, name: 'Rice Hulls')
Malt::Grain.create(origin: 'US', srm: 1, potential_sg: 1.032, name: 'Rice, Flaked')
Malt::Grain.create(origin: 'US', srm: 300, potential_sg: 1.025, name: 'Roasted Barley')
Malt::Grain.create(origin: 'US', srm: 5, potential_sg: 1.029, name: 'Rye Malt')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.036, name: 'Rye, Flaked')
Malt::Grain.create(origin: 'Germany', srm: 9, potential_sg: 1.037, name: 'Smoked Malt')
Malt::Grain.create(origin: 'Belgium', srm: 180, potential_sg: 1.030, name: 'Special B Malt')
Malt::Grain.create(origin: 'US', srm: 50, potential_sg: 1.033, name: 'Special Roast')
Malt::Sugar.create(origin: 'US', srm: 1, potential_sg: 1.046, name: 'Sugar, Table (Sucrose)')
Malt::Grain.create(origin: 'United Kingdom', srm: 27, potential_sg: 1.033, name: 'Toasted Malt')
Malt::Grain.create(origin: 'United Kingdom', srm: 10, potential_sg: 1.044, name: 'Turbinado')
Malt::Grain.create(origin: 'US', srm: 25, potential_sg: 1.034, name: 'Victory Malt')
Malt::Grain.create(origin: 'Germany', srm: 4, potential_sg: 1.036, name: 'Vienna Malt')
Malt::DryExtract.create(origin: 'US', srm: 8, potential_sg: 1.044, name: 'Wheat Dry Extract')
Malt::Extract.create(origin: 'US', srm: 8, potential_sg: 1.036, name: 'Wheat Liquid Extract')
Malt::Grain.create(origin: 'Belgium', srm: 2, potential_sg: 1.037, name: 'Wheat Malt, Bel')
Malt::Grain.create(origin: 'Germany', srm: 9, potential_sg: 1.039, name: 'Wheat Malt, Dark')
Malt::Grain.create(origin: 'Germany', srm: 2, potential_sg: 1.039, name: 'Wheat Malt, Ger')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.025, name: 'Wheat, Flaked')
Malt::Grain.create(origin: 'Germany', srm: 425, potential_sg: 1.025, name: 'Wheat, Roasted')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.036, name: 'Wheat, Torrified')
Malt::Grain.create(origin: 'US', srm: 2, potential_sg: 1.040, name: 'White Wheat Malt')

